const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const storageKey='aloeworld-lsf360-v1';
const defaults={area:120,height:2.6,perimeter:46,partitions:55,waste:10,priceM2:1000,tasks:[true,true,false,false,false,false,false,false,false,false]};
let state={...defaults,...JSON.parse(localStorage.getItem(storageKey)||'{}')};
const stages=[
  ['Preparação e projeto','Levantamento, programa, plantas e compatibilização'],
  ['Fundações e ancoragens','Base, cotas, nivelamento e pontos de fixação'],
  ['Painelização','Corte, etiquetagem e montagem dos painéis'],
  ['Piso e chassis','Vigas, travamentos e suporte das placas'],
  ['Paredes exteriores','Montantes, vãos, reforços e alinhamento'],
  ['Divisórias interiores','Distribuição, reforços e instalações'],
  ['Cobertura','Estrutura, inclinações, remates e drenagem'],
  ['Revestimentos e isolamento','Membranas, placas, fachadas e conforto'],
  ['Instalações e acabamentos','Água, eletricidade, revestimentos e equipamentos'],
  ['Controlo e entrega','Verificações, correções, documentação e receção']
];
function save(){localStorage.setItem(storageKey,JSON.stringify(state))}
function money(n){return new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n)}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function openTab(id){$$('.app-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelector('.app-shell').scrollIntoView({behavior:'smooth',block:'start'})}
$$('.app-tab').forEach(b=>b.addEventListener('click',()=>openTab(b.dataset.tab)));$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openTab(b.dataset.open)));
$('#menuButton').addEventListener('click',()=>{const n=$('#mainNav');n.classList.toggle('open');$('#menuButton').setAttribute('aria-expanded',n.classList.contains('open'))});$$('#mainNav a').forEach(a=>a.addEventListener('click',()=>$('#mainNav').classList.remove('open')));
function renderTasks(){const list=$('#taskList');list.innerHTML=stages.map((s,i)=>`<label class="task ${state.tasks[i]?'done':''}"><input type="checkbox" data-task="${i}" ${state.tasks[i]?'checked':''}><span class="task-number">${String(i+1).padStart(2,'0')}</span><span><b>${s[0]}</b><small>${s[1]}</small></span><span class="badge">${state.tasks[i]?'Concluída':'Pendente'}</span></label>`).join('');$$('[data-task]').forEach(c=>c.addEventListener('change',()=>{state.tasks[+c.dataset.task]=c.checked;save();renderTasks();renderDashboard()}));const done=state.tasks.filter(Boolean).length;$('#plannerSummary').textContent=`${done} de ${stages.length} etapas concluídas`}
function renderDashboard(){const done=state.tasks.filter(Boolean).length,p=Math.round(done/stages.length*100);$('#progressText').textContent=p+'%';$('#progressBar').style.width=p+'%';$('#dashboardArea').textContent=state.area+' m²';$('#dashboardCost').textContent=money(state.area*state.priceM2);$('#stageList').innerHTML=stages.slice(0,5).map((s,i)=>{const value=state.tasks[i]?100:(i===done?35:0);return `<div class="stage-item"><span>${s[0]}</span><div class="mini-progress"><i style="width:${value}%"></i></div><b>${value}%</b></div>`}).join('')}
function syncInputs(){['area','height','perimeter','partitions','waste','priceM2'].forEach(id=>$('#'+id).value=state[id])}
function calculate(){['area','height','perimeter','partitions','waste','priceM2'].forEach(id=>state[id]=Math.max(0,Number($('#'+id).value)||0));save();const f=1+state.waste/100;const wallArea=(state.perimeter+state.partitions*2)*state.height;const extArea=state.perimeter*state.height;const studs=Math.ceil(((state.perimeter+state.partitions*2)/.6)*f);const tracks=Math.ceil((state.perimeter*2+state.partitions*4)*f);const osb=Math.ceil((state.area/3.125)*f);const plaster=Math.ceil((wallArea/3)*f);const insulation=Math.ceil((wallArea+state.area)*f);const screws=Math.ceil((wallArea*18+state.area*12)*f);const roof=Math.ceil(state.area*1.12*f);const cost=state.area*state.priceM2;const data=[['Montantes C',studs,'un. estimadas'],['Guias U',tracks,'m lineares'],['Placas OSB 1250×2500',osb,'un. estimadas'],['Placas interiores',plaster,'un. estimadas'],['Isolamento',insulation,'m² estimados'],['Parafusos',screws,'un. estimadas'],['Cobertura',roof,'m² estimados'],['Área de paredes',Math.ceil(wallArea*f),'m² c/ desperdício'],['Custo indicativo',money(cost),'configurável']];$('#resultsGrid').innerHTML=data.map(d=>`<div class="result"><span>${d[0]}</span><b>${d[1]}</b><small>${d[2]}</small></div>`).join('');renderDashboard();toast('Estimativa atualizada')}
$('#calculateButton').addEventListener('click',calculate);$('#resetCalc').addEventListener('click',()=>{Object.assign(state,{area:120,height:2.6,perimeter:46,partitions:55,waste:10,priceM2:1000});save();syncInputs();calculate()});$('#clearPlan').addEventListener('click',()=>{state.tasks=Array(10).fill(false);save();renderTasks();renderDashboard();toast('Progresso limpo')});
function answer(q){const t=q.toLowerCase();if(t.includes('chão')||t.includes('piso')||t.includes('osb'))return 'Para o piso, é comum usar OSB estrutural adequado à classe de serviço e à distância entre vigas. A espessura deve ser definida pelo projeto e pela ficha do fabricante; em muitos sistemas utiliza-se OSB3 com juntas desencontradas e fixação especificada.';if(t.includes('montante')||t.includes('perfil'))return 'Como estimativa preliminar, pode dividir o comprimento total das paredes pelo espaçamento entre montantes, normalmente 0,40 m ou 0,60 m, e acrescentar reforços de cantos, encontros e vãos. A quantidade final deve seguir o projeto de painelização.';if(t.includes('cobertura')||t.includes('telhado'))return 'Antes da cobertura devem estar confirmados: fundações e cotas, chassis/piso, paredes aprumadas, contraventamentos, ligações entre painéis, vergas e apoios. Só depois se monta a estrutura de cobertura e os respetivos remates.';if(t.includes('isolamento')||t.includes('térmic'))return 'O desempenho depende do conjunto completo: isolamento entre montantes, correção das pontes térmicas, membrana de água e vento, barreira ou controlo de vapor quando aplicável, estanquidade e revestimentos.';if(t.includes('parafuso')||t.includes('fixa'))return 'A escolha da fixação depende da espessura dos perfis, tipo de ligação, ambiente e revestimento. Devem ser usados parafusos compatíveis com aço galvanizado e com capacidade declarada pelo fabricante.';return 'Posso ajudar a organizar a questão por etapa de obra. Indique a área, tipo de elemento — piso, parede, cobertura ou revestimento — e o material ou dúvida concreta. Na versão final, este assistente poderá consultar os manuais e projetos AloeWorld.'}
function sendChat(text){if(!text.trim())return;const chat=$('#chat');chat.insertAdjacentHTML('beforeend',`<div class="message user"><p>${text.replace(/[<>]/g,'')}</p></div>`);setTimeout(()=>{chat.insertAdjacentHTML('beforeend',`<div class="message bot"><b>AloeWorld Assistente</b><p>${answer(text)}</p></div>`);chat.scrollTop=chat.scrollHeight},250);chat.scrollTop=chat.scrollHeight}
$('#chatForm').addEventListener('submit',e=>{e.preventDefault();const i=$('#chatInput');sendChat(i.value);i.value=''});$$('.suggestions button').forEach(b=>b.addEventListener('click',()=>sendChat(b.textContent)));
$('#leadForm').addEventListener('submit',e=>{e.preventDefault();const data={name:$('#leadName').value,phone:$('#leadPhone').value,email:$('#leadEmail').value,location:$('#leadLocation').value,area:$('#leadArea').value,type:$('#leadType').value,message:$('#leadMessage').value};const text=`PEDIDO DE PROPOSTA — ALOEWORLD LSF 360\n\nNome: ${data.name}\nTelefone: ${data.phone}\nEmail: ${data.email||'-'}\nLocal da obra: ${data.location||'-'}\nÁrea: ${data.area||'-'} m²\nTipologia: ${data.type}\n\nDescrição:\n${data.message||'-'}`;const out=$('#leadOutput');out.style.display='block';out.textContent=text;$('#whatsappLink').href='https://wa.me/351968917391?text='+encodeURIComponent(text);localStorage.setItem('aloeworld-lead-draft',JSON.stringify(data));toast('Pedido preparado para envio')});
$('#whatsappLink').addEventListener('click',e=>{if(!e.currentTarget.href){e.preventDefault();toast('Preencha e prepare primeiro o pedido')}});
syncInputs();renderTasks();renderDashboard();calculate();if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});
